apiVersion: v1
kind: ConfigMap
metadata:
  name: zotoci-config
  namespace: zotoci
data:
  config.json: |-    
    {
      "storage": { 
        "rootDirectory": "/var/lib/registry" 
      },
      "http": { 
        "address": "0.0.0.0", 
        "port": "5000",
        "auth": {
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        },
        "accessControl": {
          "repositories": {
            "**": {
              "policies": [{
                "users": ["user"],
                "actions": ["read", "create", "update"]
              }],
              "defaultPolicy": ["read", "create"]
            }
          },
          "adminPolicy": {
            "users": [ "admin" ],
            "actions": [ "read", "create", "update", "delete" ]
          }
        }
      },
      "log": { 
        "level": "debug" 
      },
      "extensions": {
        "ui": { "enable": true },
        "search": { "enable": true }
      }
    }